//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringDae
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public LOCATION()
        {
            this.ENTITY_INVESTIGATION_ENVIRONMENT = new HashSet<ENTITY_INVESTIGATION_ENVIRONMENT>();
            this.ENTITY_NOTES = new HashSet<ENTITY_NOTES>();
            this.ENTITY_QUESTIONS = new HashSet<ENTITY_QUESTIONS>();
            this.ENTITY_REFERENCE_SOURCE = new HashSet<ENTITY_REFERENCE_SOURCE>();
            this.LOCATION_EVENT = new HashSet<LOCATION_EVENT>();
            this.LOCATION_GROUP = new HashSet<LOCATION_GROUP>();
            this.LOCATION_OBJECT = new HashSet<LOCATION_OBJECT>();
            this.LOCATION_PERSON = new HashSet<LOCATION_PERSON>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string LOCATION_TYPE { get; set; }
        public string STREET_ADDRESS_1 { get; set; }
        public string STREET_ADDRESS_2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string POSTAL_CODE { get; set; }
        public string COUNTRY { get; set; }
        public string COUNTY { get; set; }
        public string COORDINATES { get; set; }
        public System.DateTime Created_date { get; set; }
        public int Created_by { get; set; }
        public Nullable<int> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public int ID_ENVIRONMENT { get; set; }
    
        public virtual ICollection<ENTITY_INVESTIGATION_ENVIRONMENT> ENTITY_INVESTIGATION_ENVIRONMENT { get; set; }
        public virtual ICollection<ENTITY_NOTES> ENTITY_NOTES { get; set; }
        public virtual ICollection<ENTITY_QUESTIONS> ENTITY_QUESTIONS { get; set; }
        public virtual ICollection<ENTITY_REFERENCE_SOURCE> ENTITY_REFERENCE_SOURCE { get; set; }
        public virtual Environment Environment { get; set; }
        public virtual ICollection<LOCATION_EVENT> LOCATION_EVENT { get; set; }
        public virtual ICollection<LOCATION_GROUP> LOCATION_GROUP { get; set; }
        public virtual ICollection<LOCATION_OBJECT> LOCATION_OBJECT { get; set; }
        public virtual ICollection<LOCATION_PERSON> LOCATION_PERSON { get; set; }
    }
}
