//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringDae
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJECT
    {
        public OBJECT()
        {
            this.ENTITY_INVESTIGATION_ENVIRONMENT = new HashSet<ENTITY_INVESTIGATION_ENVIRONMENT>();
            this.ENTITY_NOTES = new HashSet<ENTITY_NOTES>();
            this.ENTITY_QUESTIONS = new HashSet<ENTITY_QUESTIONS>();
            this.ENTITY_REFERENCE_SOURCE = new HashSet<ENTITY_REFERENCE_SOURCE>();
            this.LOCATION_OBJECT = new HashSet<LOCATION_OBJECT>();
            this.OBJECT_EVENT = new HashSet<OBJECT_EVENT>();
            this.OBJECT_GROUP = new HashSet<OBJECT_GROUP>();
            this.PERSON_OBJECT = new HashSet<PERSON_OBJECT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string IDENTIFIER { get; set; }
        public string ID_TYPE { get; set; }
        public string Description { get; set; }
        public string OBJECT_STATUS { get; set; }
        public string SCALE { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<int> IMPORTANCE { get; set; }
        public int ID_OBJECT_TYPE { get; set; }
        public Nullable<int> ID_IRS { get; set; }
        public Nullable<int> ID_IS { get; set; }
        public System.DateTime Created_date { get; set; }
        public int Created_by { get; set; }
        public Nullable<int> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public int ID_ENVIRONMENT { get; set; }
    
        public virtual ICollection<ENTITY_INVESTIGATION_ENVIRONMENT> ENTITY_INVESTIGATION_ENVIRONMENT { get; set; }
        public virtual ICollection<ENTITY_NOTES> ENTITY_NOTES { get; set; }
        public virtual ICollection<ENTITY_QUESTIONS> ENTITY_QUESTIONS { get; set; }
        public virtual ICollection<ENTITY_REFERENCE_SOURCE> ENTITY_REFERENCE_SOURCE { get; set; }
        public virtual Environment Environment { get; set; }
        public virtual Investigation_status Investigation_status { get; set; }
        public virtual InvestigationRelationship_status InvestigationRelationship_status { get; set; }
        public virtual ICollection<LOCATION_OBJECT> LOCATION_OBJECT { get; set; }
        public virtual ICollection<OBJECT_EVENT> OBJECT_EVENT { get; set; }
        public virtual ICollection<OBJECT_GROUP> OBJECT_GROUP { get; set; }
        public virtual OBJECT_TYPES OBJECT_TYPES { get; set; }
        public virtual ICollection<PERSON_OBJECT> PERSON_OBJECT { get; set; }
    }
}
