//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringDae
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_GROUP_TYPE
    {
        public PERSON_GROUP_TYPE()
        {
            this.PERSON_GROUP = new HashSet<PERSON_GROUP>();
        }
    
        public string PG_TYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime Created_date { get; set; }
        public int Created_by { get; set; }
        public Nullable<int> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
    
        public virtual ICollection<PERSON_GROUP> PERSON_GROUP { get; set; }
    }
}
