//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringDae
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_ID
    {
        public int ID { get; set; }
        public string Note { get; set; }
        public string Description { get; set; }
        public System.DateTime Created_date { get; set; }
        public int Created_by { get; set; }
        public Nullable<int> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public string ID_TYPE { get; set; }
        public int ID_PERSON { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual PERSON_ID_TYPES PERSON_ID_TYPES { get; set; }
    }
}
