//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringDae
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_ATTRIBUTION
    {
        public int ID { get; set; }
        public string ATTRIBUTION_TYPE { get; set; }
        public Nullable<int> ID_NOTE { get; set; }
        public int ID_PERSON { get; set; }
        public Nullable<int> ID_QUESTIONS { get; set; }
        public System.DateTime Created_date { get; set; }
        public int Created_by { get; set; }
        public Nullable<int> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public Nullable<int> ID_INVESTIGATION { get; set; }
        public Nullable<int> ID_ENVIRONMENT { get; set; }
    
        public virtual Environment Environment { get; set; }
        public virtual Investigation Investigation { get; set; }
        public virtual NOTE NOTE { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual QUESTION QUESTION { get; set; }
    }
}
