//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringDae
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public PERSON()
        {
            this.ENTITY_INVESTIGATION_ENVIRONMENT = new HashSet<ENTITY_INVESTIGATION_ENVIRONMENT>();
            this.ENTITY_NOTES = new HashSet<ENTITY_NOTES>();
            this.ENTITY_QUESTIONS = new HashSet<ENTITY_QUESTIONS>();
            this.ENTITY_REFERENCE_SOURCE = new HashSet<ENTITY_REFERENCE_SOURCE>();
            this.LOCATION_PERSON = new HashSet<LOCATION_PERSON>();
            this.PERSON_ATTRIBUTION = new HashSet<PERSON_ATTRIBUTION>();
            this.PERSON_EVENT = new HashSet<PERSON_EVENT>();
            this.PERSON_GROUP = new HashSet<PERSON_GROUP>();
            this.PERSON_ID = new HashSet<PERSON_ID>();
            this.PERSON_OBJECT = new HashSet<PERSON_OBJECT>();
            this.PERSON_PERSON = new HashSet<PERSON_PERSON>();
            this.PERSON_PERSON1 = new HashSet<PERSON_PERSON>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string LAST_NAME { get; set; }
        public string IDENTIFIER { get; set; }
        public string ID_TYPE { get; set; }
        public string Description { get; set; }
        public string SCALE { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public string RACE { get; set; }
        public string HAIR_COLOR { get; set; }
        public string EYE_COLOR { get; set; }
        public string COMPLEXTION { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public Nullable<System.DateTime> DATE_OF_DEATH { get; set; }
        public string PERSON_STATUS { get; set; }
        public Nullable<int> IMPORTANCE { get; set; }
        public Nullable<int> ID_IRS { get; set; }
        public Nullable<int> ID_IS { get; set; }
        public System.DateTime Created_date { get; set; }
        public int Created_by { get; set; }
        public Nullable<int> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public int ID_ENVIRONMENT { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> Age_as_of { get; set; }
    
        public virtual ICollection<ENTITY_INVESTIGATION_ENVIRONMENT> ENTITY_INVESTIGATION_ENVIRONMENT { get; set; }
        public virtual ICollection<ENTITY_NOTES> ENTITY_NOTES { get; set; }
        public virtual ICollection<ENTITY_QUESTIONS> ENTITY_QUESTIONS { get; set; }
        public virtual ICollection<ENTITY_REFERENCE_SOURCE> ENTITY_REFERENCE_SOURCE { get; set; }
        public virtual Environment Environment { get; set; }
        public virtual Investigation_status Investigation_status { get; set; }
        public virtual InvestigationRelationship_status InvestigationRelationship_status { get; set; }
        public virtual ICollection<LOCATION_PERSON> LOCATION_PERSON { get; set; }
        public virtual ICollection<PERSON_ATTRIBUTION> PERSON_ATTRIBUTION { get; set; }
        public virtual ICollection<PERSON_EVENT> PERSON_EVENT { get; set; }
        public virtual ICollection<PERSON_GROUP> PERSON_GROUP { get; set; }
        public virtual ICollection<PERSON_ID> PERSON_ID { get; set; }
        public virtual PERSON_ID_TYPES PERSON_ID_TYPES { get; set; }
        public virtual ICollection<PERSON_OBJECT> PERSON_OBJECT { get; set; }
        public virtual ICollection<PERSON_PERSON> PERSON_PERSON { get; set; }
        public virtual ICollection<PERSON_PERSON> PERSON_PERSON1 { get; set; }
    }
}
