//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringDae
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_ID_TYPES
    {
        public PERSON_ID_TYPES()
        {
            this.PERSON_ID = new HashSet<PERSON_ID>();
            this.PERSONS = new HashSet<PERSON>();
        }
    
        public string ID_TYPE { get; set; }
        public string Description { get; set; }
        public System.DateTime Created_date { get; set; }
        public int Created_by { get; set; }
        public Nullable<int> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
    
        public virtual ICollection<PERSON_ID> PERSON_ID { get; set; }
        public virtual ICollection<PERSON> PERSONS { get; set; }
    }
}
