//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringDae
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stringDaeEntities : DbContext
    {
        public stringDaeEntities()
            : base("name=stringDaeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ENTITY_INVESTIGATION_ENVIRONMENT> ENTITY_INVESTIGATION_ENVIRONMENT { get; set; }
        public DbSet<ENTITY_NOTES> ENTITY_NOTES { get; set; }
        public DbSet<ENTITY_QUESTIONS> ENTITY_QUESTIONS { get; set; }
        public DbSet<ENTITY_REFERENCE_SOURCE> ENTITY_REFERENCE_SOURCE { get; set; }
        public DbSet<ENTITY_TYPES> ENTITY_TYPES { get; set; }
        public DbSet<Environment> Environments { get; set; }
        public DbSet<EVENT> EVENTS { get; set; }
        public DbSet<GROUP_EVENT> GROUP_EVENT { get; set; }
        public DbSet<GROUP> GROUPS { get; set; }
        public DbSet<Investigation> Investigations { get; set; }
        public DbSet<Investigation_status> Investigation_status { get; set; }
        public DbSet<InvestigationRelationship_status> InvestigationRelationship_status { get; set; }
        public DbSet<LOCATION_EVENT> LOCATION_EVENT { get; set; }
        public DbSet<LOCATION_GROUP> LOCATION_GROUP { get; set; }
        public DbSet<LOCATION_OBJECT> LOCATION_OBJECT { get; set; }
        public DbSet<LOCATION_PERSON> LOCATION_PERSON { get; set; }
        public DbSet<LOCATION_PERSON_TYPE> LOCATION_PERSON_TYPE { get; set; }
        public DbSet<LOCATION> LOCATIONS { get; set; }
        public DbSet<NOTE> NOTES { get; set; }
        public DbSet<OBJECT_EVENT> OBJECT_EVENT { get; set; }
        public DbSet<OBJECT_GROUP> OBJECT_GROUP { get; set; }
        public DbSet<OBJECT_TYPES> OBJECT_TYPES { get; set; }
        public DbSet<OBJECT> OBJECTS { get; set; }
        public DbSet<PERSON_ATTRIBUTION> PERSON_ATTRIBUTION { get; set; }
        public DbSet<PERSON_EVENT> PERSON_EVENT { get; set; }
        public DbSet<PERSON_GROUP> PERSON_GROUP { get; set; }
        public DbSet<PERSON_GROUP_TYPE> PERSON_GROUP_TYPE { get; set; }
        public DbSet<PERSON_ID> PERSON_ID { get; set; }
        public DbSet<PERSON_ID_TYPES> PERSON_ID_TYPES { get; set; }
        public DbSet<PERSON_OBJECT> PERSON_OBJECT { get; set; }
        public DbSet<PERSON_PERSON> PERSON_PERSON { get; set; }
        public DbSet<PERSON> PERSONS { get; set; }
        public DbSet<QUESTION> QUESTIONS { get; set; }
        public DbSet<REFERENCE_SOURCE> REFERENCE_SOURCE { get; set; }
        public DbSet<RELATIONSHIP> RELATIONSHIPs { get; set; }
        public DbSet<STOCK_GROUP_TYPES> STOCK_GROUP_TYPES { get; set; }
        public DbSet<STOCK_LOCATION_TYPES> STOCK_LOCATION_TYPES { get; set; }
        public DbSet<STOCK_REASONS_FOR_INCLUSION> STOCK_REASONS_FOR_INCLUSION { get; set; }
        public DbSet<TIMELINE_EVENT> TIMELINE_EVENT { get; set; }
        public DbSet<TIMELINE> TIMELINES { get; set; }
        public DbSet<User> Users { get; set; }

        public DbSet<StringDae.PERSON> People { get; set; }

        public DbSet<StringDae.GROUP> GROUPs { get; set; }
    }
}
